### PR TITLE
feat: Add content export for dashboard and look only

### PR DESCRIPTION
**Pull request by danieldiamond**
## Description
Resolves https://github.com/looker-open-source/looker_deployer/issues/107

* Add `export_content_group` which includes `folders`, `dashboards` and `looks`
* Add `content_export` function to `cat` dashboards & looks and store them locally
* Add tests
* Update `setup.py` to include python_versions `3.10`

### CODE REVIEW

**Comment by danieldiamond** [comment]
@jannarobertson-bytecode @AdamMinton either of you able to assist?

**Comment by danieldiamond** [comment]
Also considering 

https://github.com/looker-open-source/gzr#attention

> This project is on a path towards deprecation in favor of [Looker Deployer](https://github.com/looker-open-source/looker_deployer). New users should start with Looker Deployer if possible. 
>
> Looker Deployer is based on newer Looker APIs and is intended to provide a superset of CLI functionality, including content migration features.

Should we replace the `gzr` pinned project on https://github.com/looker-open-source

**Comment by danieldiamond** [comment]
@AdamMinton any chance you can assist with this one?

**Review by AdamMinton — APPROVED** [review]
LGTM

**Comment by AdamMinton** [comment]
re: https://github.com/looker-open-source/looker_deployer/pull/108#issuecomment-1423685791

The goal last year was to remove gzr entirely, but it's been a lower priority as there is no dedicated team for maintenance and new features. There is a [new export endpoint](https://developers.looker.com/api/explorer/4.0/methods/Dashboard/dashboard_lookml) and [new import endpoint](https://developers.looker.com/api/explorer/4.0/methods/Dashboard/import_dashboard_from_lookml) that should speed up this development.

**Pull request merged**
